version: '0.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
  - i3
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
clone_depth: 1
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build ./src
test_script:
  - cmd: dotnet test .\src\DbDataReaderExtension.Test\
deploy: off
